[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from   = "/api/payfast-itn"
  to     = "/.netlify/functions/payfast-itn"
  status = 200

[[redirects]]
  from       = "/*"
  to         = "/index.html"
  status     = 200
  conditions = {Country = ["ZA"]}

[[redirects]]
  from   = "/*"
  to     = "/unavailable.html"
  status = 200
